headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[build]
edge_functions = "/Users/reedlarson/.openclaw/workspace/projects/edina-boys-golf/repo/netlify/edge-functions"
publish = "/Users/reedlarson/.openclaw/workspace/projects/edina-boys-golf/repo/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[headers]]
for = "/index.html"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/version.json"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/index.html"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/version.json"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]